New language! Spanish
Lattyware/massivedecks pull request #235
Opened 2021-07-05 19:54 UTC by carlesvimas

Language added following this guide [.](https://github.com/Lattyware/massivedecks/wiki/Translation). I'm pretty sure it's ready for implementation

2021-07-05 19:55 UTC, carlesvimas commented
Would love to see it live since I really enjoy this game despite the lack of my language.

2021-07-07 22:44 UTC, Lattyware commented
Thanks for this contribution! Looks great.
I've been ill for a bit and so not sure when I'll get the moment to merge this through, but I'll do so as soon as possible.

2021-07-20 23:55 UTC, Polsaker requested changes
This translation probably needs some more proofreading. These were the errors I found after a quick look

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Un libro enecerrado en un circulo por una flecha de reciclaje." ]
```suggestion
            [ Text "Un libro encerrado en un circulo por una flecha de reciclaje." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "El proyecto de github" ]
```suggestion
            [ Text "El proyecto de Github" ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Otra persona esta usando este nombre en la partida—porfavor elija otro diferente." ]
```suggestion
            [ Text "Otra persona está usando este nombre en la partida—por favor elija otro diferente." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Necesitas una contraseña para entrar a la partida. Preguntasela a la persona que te ha invitado." ]
```suggestion
            [ Text "Necesitas una contraseña para entrar a la partida. Pídesela a la persona que te ha invitado." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Como jugar." ]
```suggestion
            [ Text "Cómo jugar." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Cuantas ", ref (nounUnknownQuantity Point), Text " cuesta reiniciar la baraja." ]
```suggestion
            [ Text "Cuántos ", ref (nounUnknownQuantity Point), Text " cuesta reiniciar la baraja." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "El numero de "
```suggestion
            [ Text "El número de "
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Numero de Bots en la partida." ]
```suggestion
            [ Text "Número de Bots en la partida." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            , Text " roba multiples "
```suggestion
            , Text " roba múltiples "
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            , Text " para que te notifique. Esto solo se usará mientras tengas el juego abierto y esto este activado."
```suggestion
            , Text " para que te notifique. Esto solo se usará mientras tengas el juego abierto y mientras esto esté activado."
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Tu navegador no puede comprobar la visivilidad de la página." ]
```suggestion
            [ Text "Tu navegador no puede comprobar la visibilidad de la página." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Preguntale a la persona que te ha invitado por el ", ref GameCodeTerm, Text " de la partida." ]
```suggestion
            [ Text "Pregúntale a la persona que te ha invitado por el ", ref GameCodeTerm, Text " de la partida." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "¡Unirse a la sala!" ]
```suggestion
            [ Text "¡Unirse a la partida!" ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Numero de likes recibidos."
```suggestion
            [ Text "Número de \"me gusta\" recibidos."
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Con el número de jugadores en la partida, necesitarás almenos "
```suggestion
            [ Text "Con el número de jugadores en la partida, necesitarás al menos "
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ ref source, Text " ha fallado en conseguir la baraja. Porfavor prueba más tarde o cambia de proveedor." ]
```suggestion
            [ ref source, Text " ha fallado en conseguir la baraja. Por favor prueba más tarde o cambia de proveedor." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Un codigo de baraja tiene que ser de al menos 5 caracteres." ]
```suggestion
        ManyDecksDeckCodeTitle ->
            [ Text "Código de la Baraja" ]

        ManyDecksDeckCodeShort ->
            [ Text "Un código de baraja tiene que ser de al menos 5 caracteres." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +                [ Text "El numero de "
```suggestion
                [ Text "El número de "
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Desabilitar ", ref HouseRuleRandoCardrissian ]
```suggestion
            [ Text "Deshabilitar ", ref HouseRuleComedyWriter ]

        DisableRando ->
            [ Text "Deshabilitar ", ref HouseRuleRandoCardrissian ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Juego público" ]
```suggestion
            [ Text "Partida pública" ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "El valor de la configuración no es valido." ]
```suggestion
            [ Text "El valor de la configuración no es válido." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "Lider muestra las respuestas" ]
```suggestion
            [ Text "Zar revela las jugadas" ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "El servidor dio una respuesta que no esperavamos." ]
```suggestion
            [ Text "El servidor dio una respuesta que no esperábamos." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "El servidor nos dió un cambio de configuración para una versión diferente de la que esperavamos." ]
```suggestion
            [ Text "El servidor nos dió un cambio de configuración para una versión diferente de la que esperábamos." ]
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "El codigo que has introducido ("
```suggestion
            [ Text "El código que has introducido ("
```

2021-07-20 23:55 UTC, Polsaker commented on client/src/elm/MassiveDecks/Strings/Languages/Es.elm
> +            [ Text "No havian suficientes cartas en la baraja para todos los jugadores. Prueba de añadir más en la configuración." ]
```suggestion
            [ Text "No habían suficientes cartas en la baraja para todos los jugadores. Prueba de añadir más en la configuración." ]
```

2021-09-19 12:13 UTC, Lattyware commented
This has been merged in as 651f3d1d91d0038bc9b837158de1d98182c5199b. If there are further updates or fixes, please feel free to open a new PR.

Thanks for the contribution, and sorry for the long time getting it merged in.

2021-09-19 12:13 UTC, closed without merging